### ISSUE TITLE
LiquidMS web browser (fancy) isn't updating server names

### ISSUE THREAD

**Issue by InFTord** [zibonbadi/liquidms#21]
I have a server (Infinite Central), and it doesn't has this name in web browser:
![изображение](https://user-images.githubusercontent.com/60395110/203314857-199ff428-df1e-479d-9eb0-dadbb93b9123.png)

**Comment by InFTord** [comment]
NOTE: in game, it does show up correctly

**Comment by zibonbadi** [comment]
As there are currently *two* possible server browsers shipped with LiquidMS, as well as the ability to host LiquidMS using a custom one if so desired, I've updated the issue's title to reflect that this issue is centered around the `fancy` browser. The other one - `fast` - is not meant to query live information and will as such not be affected by this issue.

**Comment by zibonbadi** [comment]
A new update to the fast browser has just been released. Judging from internal development tests, it should now fix the issue. It seems that the main issue lied in the server name not being transferred after a successful query, rather than being an issue with the `fancy` browser's queries themselves.

Please test for yourselves to verify and report any further issues. Thank you.

**Comment by InFTord** [comment]
![изображение](https://user-images.githubusercontent.com/60395110/205484176-5574e3de-d835-4e4d-930b-691322446a4b.png)
it did got fixed! ty!
